---
spring:
  profiles: default
  application:
    name: user
    dna:
      default-size-arr: 6
      default-count-mutant: 2
      default-diagonal-size: 6
  datasource:
    driverClassName: org.h2.Driver
    url: "jdbc:h2:mem:%s;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    password: "root"
    username: "root"
    testOnBorrow: true
    testWhileIdle: true
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000